// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { trackError, monitorSupabaseConnection } from '@/lib/monitoring';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if environment variables are properly loaded
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const error = new Error('Missing Supabase environment variables');
  trackError(error, {
    SUPABASE_URL_EXISTS: !!SUPABASE_URL,
    SUPABASE_KEY_EXISTS: !!SUPABASE_PUBLISHABLE_KEY,
  });
  // Fail fast: never fall back to a shared demo project
  throw error;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL as string,
  SUPABASE_PUBLISHABLE_KEY as string,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

// Monitor Supabase connection status
supabase.auth.onAuthStateChange(() => {
  monitorSupabaseConnection(true);
});

// Add error handling for failed requests
const originalRequest = supabase.rest.request;
supabase.rest.request = async function(...args) {
  try {
    return await originalRequest.apply(this, args);
  } catch (error) {
    trackError(error as Error, { 
      type: 'supabase_request_error', 
      args: JSON.stringify(args)
    });
    throw error;
  }
};
